# Generated by Django 4.0.4 on 2022-04-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapyitem',
            old_name='data',
            new_name='text',
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='author',
            field=models.CharField(default='', max_length=512),
        ),
    ]
